#!/usr/bin/env bash
DOVE_CACHE_PATH="$(pwd)/.dove_cache"
DOVE_LOCK_FILE="$DOVE_CACHE_PATH/dove.lock"

function acquire_lock() {
    mkdir -p $DOVE_CACHE_PATH
    exec 99>"$DOVE_LOCK_FILE"
    flock -n 99
    RC=$?
    if [ "$RC" != 0 ]; then
        printf "Dove is already running for locally..\n"
        exit 1
    fi
}

acquire_lock

if [ $1 == "remove" ]; then
    if [[ $EUID -ne 0 ]]; then
        sudo rm $(which dove)
    else
        rm $(which dove)
    fi
elif [[ $EUID -ne 0 ]]; then
    echo "installing dove for $(basename -- ~)"
    cp ./dove.py ~/bin/dove
    echo "done"
else
    echo "installing dove as root"
    sudo cp ./dove.py /bin/dove
    echo "done"
fi

# removing cache
rm -r $DOVE_CACHE_PATH
exit 0